package GUI;
import static javax.swing.JOptionPane.showMessageDialog;

import java.util.ArrayList;
import java.util.List;

import javax.swing.BoxLayout;
import javax.swing.JPanel;

import client.Game;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Acer Customer
 */
public class RoomPanel extends javax.swing.JPanel {
	
    /**
     * Creates new form GUItest
     */
    public RoomPanel() {
        initComponents();
    }
    
    public void UpdateUserList(String[] users) {
    	userList.setModel(new javax.swing.AbstractListModel<String>() {
            public int getSize() { return users.length; }
            public String getElementAt(int i) { return users[i]; }
        });
    }
    
    public void UpdateChatLog(String[] messages) {
    	for(; chatLogIndex < messages.length; chatLogIndex++) {
    		String[] messageBreakdown = messages[chatLogIndex].split(",");
    		if(messageBreakdown[1].equals("chat"))
    			chatBoxHistory.append("\n["+messageBreakdown[0]+"]: " + messageBreakdown[2]);
    		else if (messageBreakdown[1].equals("newUser"))
    			chatBoxHistory.append("\n"+messageBreakdown[0]+" joined");
    		else if (messageBreakdown[1].equals("leaveRoom"))
    			chatBoxHistory.append("\n"+messageBreakdown[0]+" left");
    	}
    	chatBoxHistory.setCaretPosition(chatBoxHistory.getDocument().getLength());
    }
    
    public String[] GetMessages() {
    	String[] messages = new String[currentMessages.size()];
    	messages = currentMessages.toArray(messages);
    	currentMessages.removeAll(currentMessages);
    	return messages;
    }

    public Integer[] GetGames() {
    	Integer[] games = new Integer[startGames.size()];
    	games = startGames.toArray(games);
    	startGames.removeAll(startGames);
    	return games;
    }
    
    public void SetGame(Game g, int gameType) {
    	if(gamePanels[gameType] == null) {
    		switch(gameType) {
    			case 0:
    				gamePanels[gameType] = new TicTacToePanel(g);
    				gameTabs.addTab("TicTacToe", gamePanels[gameType]);
    				break;
    			case 1:
    				gamePanels[gameType] = new ChessPanel(g);
    				gameTabs.addTab("Chess", gamePanels[gameType]);
    				break;
    			case 2:
    				gamePanels[gameType] = new CheckersPanel(g);
    				gameTabs.addTab("Checkers", gamePanels[gameType]);
    				break;
    		}
    	}
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sideTabs = new javax.swing.JTabbedPane();
        gameTabs = new javax.swing.JTabbedPane();
        userTab = new javax.swing.JScrollPane();
        gameChoiceTab = new javax.swing.JScrollPane();
        game0Button = new javax.swing.JButton();
        game1Button = new javax.swing.JButton();
        game2Button = new javax.swing.JButton();
        gameChoicePanel = new javax.swing.JPanel();
        userList = new javax.swing.JList<>();
        chatPane = new javax.swing.JScrollPane();
        chatBoxHistory = new javax.swing.JTextArea();
        chatBoxSend = new javax.swing.JTextField();
        chatButtonSend = new javax.swing.JButton();
        gamePane = new javax.swing.JScrollPane();
        currentMessages = new ArrayList<String>();
        startGames = new ArrayList<Integer>();
        gamePanels = new JPanel[4];

        userTab.setViewportView(userList);

        sideTabs.addTab("Users", userTab);
        sideTabs.addTab("Games", gameChoiceTab);

        chatBoxHistory.setEditable(false);
        chatBoxHistory.setColumns(20);
        chatBoxHistory.setLineWrap(true);
        chatBoxHistory.setRows(5);
        chatBoxHistory.setText("");
        chatPane.setViewportView(chatBoxHistory);
        
        chatBoxSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chatBoxSendActionPerformed(evt);
            }
        });

        chatButtonSend.setText("-->");
        chatButtonSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chatButtonSendActionPerformed(evt);
            }
        });
        
        gameChoicePanel.setLayout(new BoxLayout(gameChoicePanel, BoxLayout.Y_AXIS));
        
        game0Button.setText("TicTacToe");
        game0Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startTicTacToe(evt);
            }
        });
        gameChoicePanel.add(game0Button);
        
        game1Button.setText("Chess");
        game1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startChess(evt);
            }
        });
        gameChoicePanel.add(game1Button);
        
        game2Button.setText("Checkers");
        game2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startCheckers(evt);
            }
        });
        gameChoicePanel.add(game2Button);
        
        gameChoiceTab.setViewportView(gameChoicePanel);
        
        gamePane.setViewportView(gameTabs);
        
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(sideTabs, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chatPane, javax.swing.GroupLayout.DEFAULT_SIZE, 505, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(chatBoxSend)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chatButtonSend))
                    .addComponent(gamePane))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sideTabs, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(gamePane, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(chatPane, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(chatButtonSend)
                    .addComponent(chatBoxSend, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void menuDropdownHelpMenuDragMouseEntered(javax.swing.event.MenuDragMouseEvent evt) {//GEN-FIRST:event_menuDropdownHelpMenuDragMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_menuDropdownHelpMenuDragMouseEntered

    private void helpOptionAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpOptionAboutActionPerformed
        // TODO add your handling code here:
        showMessageDialog(null, "This software was created by:\n\nRam Kammari\nArt Olsen\nNathaniel Potgiesser\nDiego Rivera\nFelix Tang");
    }//GEN-LAST:event_helpOptionAboutActionPerformed

    private void helpOptionNobodycameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpOptionNobodycameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_helpOptionNobodycameActionPerformed

    private void chatBoxSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chatBoxSendActionPerformed
        // TODO add your handling code here:
        if (!chatBoxSend.getText().equals("")){
            currentMessages.add(chatBoxSend.getText());
            chatBoxSend.setText("");
        }
        chatBoxSend.requestFocus();
    }//GEN-LAST:event_chatBoxSendActionPerformed

    private void chatButtonSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chatButtonSendActionPerformed
        // TODO add your handling code here:
        chatBoxSendActionPerformed(evt);
    }//GEN-LAST:event_chatButtonSendActionPerformed

    private void startTicTacToe(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chatButtonSendActionPerformed
        startGames.add(0);
    }
    
    private void startChess(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chatButtonSendActionPerformed
        startGames.add(1);
    }
    
    private void startCheckers(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chatButtonSendActionPerformed
        startGames.add(2);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea chatBoxHistory;
    private javax.swing.JTextField chatBoxSend;
    private javax.swing.JButton chatButtonSend;
    private javax.swing.JScrollPane chatPane;
    private javax.swing.JScrollPane gamePane;
    private javax.swing.JTabbedPane sideTabs;
    private javax.swing.JTabbedPane gameTabs;
    private javax.swing.JList<String> userList;
    private javax.swing.JScrollPane userTab;
    private javax.swing.JScrollPane gameChoiceTab;
    private javax.swing.JButton game0Button;
    private javax.swing.JButton game1Button;
    private javax.swing.JButton game2Button;
    private javax.swing.JPanel gameChoicePanel;
    private int chatLogIndex = 0;
    // End of variables declaration//GEN-END:variables
    private List<String> currentMessages;
    private List<Integer> startGames;
    private JPanel[] gamePanels;
}
